services:
  - type: web
    name: ecommerce-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
      - key: EMAIL_HOST_USER
        value: your-email@example.com
      - key: EMAIL_HOST_PASSWORD
        value: your-email-password
